# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["read.py"]

doc_url = "https://lightsquared.github.io/spect-temp/"

git_url = "https://github.com/lightsquared/spect-temp/tree/master/"

def custom_doc_links(name): return None
